/**
 * Lifecycle mapping between the A2A v1.0.1 TaskState (nine named values of a
 * numeric enum) and the io.modelcontextprotocol/tasks 2026-07-28 TaskStatus
 * (five string values).
 *
 * The A2A enum is generated by ts-proto: values are integers at runtime, a
 * wire string is not an enum member, and an unknown value collapses to the
 * sentinel UNRECOGNIZED instead of raising. Every mapping that loses
 * information reports the loss rather than absorbing it silently.
 */
import { TaskState, taskStateFromJSON } from "@a2a-js/sdk";

/** The five task statuses of the MCP tasks extension, in lifecycle order. */
export const MCP_TASK_STATUSES = [
  "working",
  "input_required",
  "completed",
  "failed",
  "cancelled",
] as const;

export type McpTaskStatus = (typeof MCP_TASK_STATUSES)[number];

/** The four A2A states from which a task never moves again (A2A 3.1.2). */
export const A2A_TERMINAL_STATES = [
  TaskState.TASK_STATE_COMPLETED,
  TaskState.TASK_STATE_FAILED,
  TaskState.TASK_STATE_CANCELED,
  TaskState.TASK_STATE_REJECTED,
] as const;

/** Raised when a value is not one of the nine named A2A task states. */
export class UnknownTaskStateError extends Error {
  readonly received: unknown;

  constructor(received: unknown) {
    super(
      `Unknown A2A task state: ${describeValue(received)}. ` +
        "Expected one of the nine named TaskState values of A2A v1.0.1.",
    );
    this.name = "UnknownTaskStateError";
    this.received = received;
  }
}

/** The outcome of mapping one A2A state onto an MCP task status. */
export interface McpStatusMapping {
  /** The MCP task status the A2A state is reported as. */
  status: McpTaskStatus;
  /** True when the mapping drops information the A2A state carried. */
  lossy: boolean;
  /** Present only when lossy: what is lost and where it survives. */
  note?: string;
}

const SUBMITTED_NOTE =
  "A2A reports the task as submitted, a state MCP has no separate status for. " +
  "The bridge reports working; the fact that no agent has picked the task up yet " +
  "survives only in the task statusMessage.";

const INPUT_REQUIRED_NOTE =
  "A2A asks for more input as free text in the task statusMessage, with no schema. " +
  "The bridge reports input_required and the elicitation form is synthesized from that " +
  "text, so the wording the agent chose survives only in the statusMessage.";

const REJECTED_NOTE =
  "A2A rejected the task instead of running it, which MCP cannot tell apart from a " +
  "failure. The bridge reports failed; the reason for the rejection survives only in " +
  "the task statusMessage.";

const AUTH_REQUIRED_NOTE =
  "A2A requires authentication before it can proceed. The bridge reports failed rather " +
  "than input_required, because MCP 2026-07-28 states that servers MUST NOT use form " +
  "mode elicitation to request sensitive information such as credentials. The " +
  "authentication instructions survive in the task statusMessage.";

const UNSPECIFIED_NOTE =
  "A2A returned the unspecified state, which carries no lifecycle information at all. " +
  "The bridge reports failed rather than guessing a lifecycle; whatever the agent sent " +
  "survives only in the task statusMessage.";

/**
 * Maps one A2A task state onto an MCP task status.
 *
 * Throws UnknownTaskStateError on UNRECOGNIZED, on any integer outside the
 * enum, and on a wire string passed where the numeric enum is expected.
 */
export function toMcpStatus(state: TaskState): McpStatusMapping {
  switch (state) {
    case TaskState.TASK_STATE_WORKING:
      return { status: "working", lossy: false };
    case TaskState.TASK_STATE_COMPLETED:
      return { status: "completed", lossy: false };
    case TaskState.TASK_STATE_FAILED:
      return { status: "failed", lossy: false };
    case TaskState.TASK_STATE_CANCELED:
      // A2A spells it with one l, MCP with two.
      return { status: "cancelled", lossy: false };
    case TaskState.TASK_STATE_SUBMITTED:
      return { status: "working", lossy: true, note: SUBMITTED_NOTE };
    case TaskState.TASK_STATE_INPUT_REQUIRED:
      return { status: "input_required", lossy: true, note: INPUT_REQUIRED_NOTE };
    case TaskState.TASK_STATE_REJECTED:
      return { status: "failed", lossy: true, note: REJECTED_NOTE };
    case TaskState.TASK_STATE_AUTH_REQUIRED:
      return { status: "failed", lossy: true, note: AUTH_REQUIRED_NOTE };
    case TaskState.TASK_STATE_UNSPECIFIED:
      return { status: "failed", lossy: true, note: UNSPECIFIED_NOTE };
    default:
      throw new UnknownTaskStateError(state);
  }
}

/**
 * The MCP task status the tasks extension reports for one A2A state.
 *
 * Deliberately different from toMcpStatus, which describes the A2A task
 * inside the result envelope. On the extension wire an A2A failure is a
 * completed MCP task whose result carries isError, because the underlying
 * tools/call did produce a result; the failed status is reserved for a
 * failure of the bridge itself.
 */
export function toTaskExtensionStatus(state: TaskState): McpTaskStatus {
  switch (state) {
    case TaskState.TASK_STATE_SUBMITTED:
    case TaskState.TASK_STATE_WORKING:
      return "working";
    case TaskState.TASK_STATE_INPUT_REQUIRED:
      return "input_required";
    case TaskState.TASK_STATE_CANCELED:
      return "cancelled";
    case TaskState.TASK_STATE_COMPLETED:
    case TaskState.TASK_STATE_FAILED:
    case TaskState.TASK_STATE_REJECTED:
    case TaskState.TASK_STATE_AUTH_REQUIRED:
    case TaskState.TASK_STATE_UNSPECIFIED:
      return "completed";
    default:
      throw new UnknownTaskStateError(state);
  }
}

/**
 * Maps an MCP task status back onto the A2A state the bridge sends. The three
 * lossy states have no inverse: they collapse onto working or failed.
 */
export function fromMcpStatus(status: McpTaskStatus): TaskState {
  switch (status) {
    case "working":
      return TaskState.TASK_STATE_WORKING;
    case "completed":
      return TaskState.TASK_STATE_COMPLETED;
    case "failed":
      return TaskState.TASK_STATE_FAILED;
    case "cancelled":
      return TaskState.TASK_STATE_CANCELED;
    case "input_required":
      return TaskState.TASK_STATE_INPUT_REQUIRED;
    default:
      throw new RangeError(
        `Unknown MCP task status: ${describeValue(status)}. ` +
          `Expected one of ${MCP_TASK_STATUSES.join(", ")}.`,
      );
  }
}

/** True for the four A2A states a task never leaves. */
export function isTerminalA2AState(state: TaskState): boolean {
  return (A2A_TERMINAL_STATES as readonly TaskState[]).includes(state);
}

/**
 * Parses the ProtoJSON form of a task state, either the SCREAMING_SNAKE_CASE
 * name or the integer. The SDK helper answers UNRECOGNIZED for anything it
 * does not know; the bridge turns that silence into an error.
 */
export function parseWireTaskState(value: string | number): TaskState {
  const parsed: TaskState = taskStateFromJSON(value);
  if (parsed === TaskState.UNRECOGNIZED) {
    throw new UnknownTaskStateError(value);
  }
  return parsed;
}

function describeValue(value: unknown): string {
  return typeof value === "string" ? JSON.stringify(value) : String(value);
}
